### ISSUE TITLE
뱃지, 장애인용 게시글 api 연결

### ISSUE THREAD

**Issue by jungmiinn** [team-dotori/guidely_client#50]
## Description

api랑 맞짱

## Todo
* [x] 뱃지 api 연결
* [x] 장애인용 게시글 연결
* [x] 댓글 연결
* [x] 댓글 입력 연결
