### ISSUE TITLE
수정된 디자인 부분 수정, 추가 디자인 추가

### ISSUE THREAD

**Issue by jungmiinn** [team-dotori/guidely_client#54]
## Description

구현 후 수정된 디자인에 대해 수정

## Todo
* [x] 게시글의 음성댓글 듣기 버튼
* [x] 점자 이미지 처리 화면 구현
* [x] 장애인용 게시물 작성 고대비 디자인 추가
* [x] 그외 자잘한 디자인 수정
