### ISSUE TITLE
지도페이지 API 연결

### ISSUE THREAD

**Issue by HyeonJunSong** [team-dotori/guidely_client#55]
## Description

지도페이지 API 및 기능 연결

## Todo
* [x] 네비게이션 바 기능 연결
* [x] API 연결 및 테스트
* [x] 신고내역 리스트 가져오기
